Feature (Address Auth Naming Convention)
autodesk-platform-services/aps-sdk-node pull request #15
Opened 2024-03-19 14:17 UTC by Arrotech

### What does this PR do?

Address naming convention for authentication SDK.

### Branch Name

**DAS-178**

2024-03-20 10:19 UTC, sajith-subramanian requested changes
A new version of the sdkmanager is now available, which contains the naming convention fix, and needs to be consumed by the sdk.

2024-03-22 08:10 UTC, srivastavarahull requested changes
1. The getUserInfo endpoint is having authorization as optional param which doesn't seems correct please confirm.
2. Looks like a new class is added i.e get-keys200-response,we usually rename 200 response classes this needs to be updated.
3.  The get-keys200-response class looks same as jwks class kindly review it .
4. In sample, I can see getUserInfo function now has an optional param for access token.

2024-03-26 11:35 UTC, sajith-subramanian approved these changes

2024-03-26 13:17 UTC, sajith-subramanian approved these changes

2024-03-26 13:30 UTC, sajith-subramanian approved these changes

2024-03-27 04:28 UTC, merged